### PR TITLE
Enable linkcheck in CI

### PR DESCRIPTION
**Pull request by wolfgangwalther**
Linkcheck is not enabled in CI, because rate-limited access to GitHub is not possible, yet.

This seems to be implemented in sphinx by now, but nixpkgs' sphinx version is not updated, yet.

### CODE REVIEW

**Comment by wolfgangwalther** [comment]
We need at least sphinx 3.4.0:

> Release 3.4.0 (released Dec 20, 2020)
> [...]
> #6629: linkcheck: The builder now handles rate limits. See :confval:`linkcheck_retry_on_rate_limit` for details.

nixpkgs is currently at 3.3.1:

https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/sphinx/default.nix

**Comment by wolfgangwalther** [comment]
Linkcheck now works as expected - rate-limited.

However one link is currently failing:

```
index: line    4) broken    https://www.paypal.com/paypalme/postgrest - Exceeded 30 redirects.
```

This link works for me in the browser - but linkcheck exceeds redirects locally, too. Requesting the link with `curl` exceeds redirects, too... - I assume this because cookies are not set after the redirect.

**Comment by steve-chavez** [comment]
I can reproduce the paypal issue with curl:

```
curl https://www.paypal.com/paypalme/postgrest
Moved Permanently. Redirecting to https://www.paypal.me/postgrest
```

When I add the chrome user agent I get the content though:

```
curl -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36"\
   https://www.paypal.com/paypalme/postgres

200

<!DOCTYPE html>
...
```

Perhaps it's possible to configure `linkcheck` user agent?

**Comment by wolfgangwalther** [comment]
Good find. I did a bit of testing... with just `-H "User-Agent: M"` it works... but once I set it to either `Curl` or `Sph`, it fails with too many redirects... seems like paypal just wants to be mean somehow.. :D

**Comment by wolfgangwalther** [comment]
Linkcheck passed in this PR... and then failed on main:

```
(           index: line  231) broken    https://supabase.io - HTTPSConnectionPool(host='supabase.io', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fea7e6b9d90>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```

I'll retry.

**Pull request merged**
