### PR TITLE
ci: switch to GitHub Actions

### PR DESCRIPTION
**Pull request by wolfgangwalther**
Will push this to the other active branches, too (v9.0, v8.0, v7.0.0) - and then try to disable circle CI.

### CODE REVIEW

**Comment by wolfgangwalther** [comment]
Mh. GitHub Actions doesn't run, yet. Maybe you have to enable it in the repo settings, @steve-chavez?

**Comment by steve-chavez** [comment]
@wolfgangwalther Hm, I see Actions enabled:

Screenshot_20220130-102209_Chrome

Maybe it has to be merged into the main branch first?

**Comment by wolfgangwalther** [comment]
Hm. I tried it on my fork and it worked there, so I guess it's fine to merge and try.

**Comment by wolfgangwalther** [comment]
Ok, that worked. However, I can't disable circleCI - you'll have to do that @steve-chavez:

> You must have admin access to stop building this project.

**Comment by wolfgangwalther** [comment]
Just confirmed it's building in PRs now, too (#496).

**Comment by wolfgangwalther** [comment]
> Ok, that worked. However, I can't disable circleCI - you'll have to do that @steve-chavez:

Could you disable circle CI on this repo? It's still trying to run and failing all checks / PRs.

**Comment by steve-chavez** [comment]
Done! I've hit the "Stop Building" button.

**Pull request merged**
