### PR TITLE
Added the link to tutorial to configure and integrate Auth0 to PostgREST

### PR DESCRIPTION
**Pull request by samkhawase**
Added the link to tutorial to configure and integrate Auth0 to PostgREST

### CODE REVIEW

**Comment by steve-chavez** [comment]
@samkhawase Overall it looks great! Also thanks a lot for providing a summary along with the link.

Here's some feedback:

So, according to [Overview of Role System](http://postgrest.org/en/v6.0/auth.html) your equivalent roles are:

- authenticator: `app_user`
- webuser: `api_user`
- anonymous: `api_anon`

However, your `app_user` is a superuser which doesn't follow the official docs. Ideally, you should create a zero privilege(NOINHERIT) user that's only capable of login to the db and switch to the other roles:

```sql
CREATE ROLE authenticator WITH NOINHERIT LOGIN PASSWORD 'password';

GRANT api_user TO authenticator;
GRANT api_anon TO authenticator;
```

Then you would use this `authenticator` in `PGRST_DB_URI`. You can change the name to anyone you prefer. `app_user` and `api_user` are easy to confuse though, so maybe use a different one from `app_user`.

The `authenticator` is integral to PostgREST security model, so I think is important to address this.

**Comment by steve-chavez** [comment]
These ones are more of nitpicks:

I see some mentions of ` PostgREST library` but it's not really a library. One apt description is: [It's a single executable binary so you don't have to install a runtime or an interpreter](https://www.compose.com/articles/your-sql-schema-is-your-json-api-with-postgrest/). I think in some parts you could leave it with just `PostgREST`(or maybe `PostgREST webserver`) instead of `PostgREST library`.

> SQL is a 46 year old battle tested technology, invented by E.F. Codd almost 5 decades ago.

Oh I believe Codd came up with the Relational Model but not SQL.

Again, these are nitpicks so feel free to address them or not :)

**Comment by steve-chavez** [comment]
Oh and one question, since you seem to know Auth0 well. Is this guide http://postgrest.org/en/v6.0/auth.html#jwt-from-auth0 still relevant? Still works?

**Comment by samkhawase** [comment]
Hi Steve,

Thanks a lot for your feedback! I've made the requested changes:
1. added `authenticator` role and removed the `app_user` as requested
2. Updated the text to say `postgREST` instead of `postgREST library`

Could you please let me know if this of ok to be merged?

I'll verify the [Auth0 guide](http://postgrest.org/en/v6.0/auth.html#jwt-from-auth0) on a separate thread and will update it if I find it outdated.

**Comment by steve-chavez** [comment]
@samkhawase LGTM! 

I'll merge now.

**Comment by steve-chavez** [comment]
@samkhawase The link to your tutorial is 404ing now. Maybe you'd like to correct it.

(Report on gitter chat: https://gitter.im/begriffs/postgrest?at=5f35c35e9ad3cd3205c7377c)

Looks like this is the correct url: https://samkhawase.com/blog/postgrest.

**Comment by samkhawase** [comment]
@steve-chavez my bad, I've updated the blog post and will send a new PR.

**Pull request merged**
