### PR TITLE
For discussion: Remove obsolete stuff

### PR DESCRIPTION
**Pull request by wolfgangwalther**
Removing a couple of things where I feel we don't need them anymore. Split up in 3 commits, because some of them might be more controversial then others ;)

1. Makefile and Pipfile: The Makefile does not seem to be used at all. If anything from that is needed, we should add nix-tools instead. The Pipfile would only make sense when not using nix, but I don't it's worth to maintain it. I tried it once, but using it failed because I have python3.8 and not 3.6 on the system. I then gave up and used nix - worked instantly. Regarding the Makefile I also checked the build-log for readthedocs, it seems to run the needed commands itself without the makefile. Should be safe to remove.

2. The chinese translation is heavily outdated - I don't think there is any value in pointing to it anymore. There's another issue with it: If you click on the zh translation on readthedocs, it will not show the version this is for anymore, but just "latest". That is very confusing at best and not helpful. It's very unlikely that this the translation will be updated anytime as it's much work. So I suggest to remove it here and from readthedocs (I don't think I can do it there, missing privileges - you would need to do that, @steve-chavez, if you agree).

3. That one might be a bit more controversial: I suggest to remove the whole section about translations from the Readme. It seems quite unlikely that there will be any other translations and we sure don't want to maintain those - we already have trouble keeping up with the english docs after all :). If anyone shows up and is heavily interested in maintaining a translation properly, they will sure get in touch, even without this section. Short: Let's focus more on getting the english translations up2date instead of carrying old stuff around.

Thoughts?

### CODE REVIEW

**Comment by wolfgangwalther** [comment]
Force push, nothing changed to trigger an automated readthedocs build. Let's see whether that works.

**Comment by wolfgangwalther** [comment]
> Force push, nothing changed to trigger an automated readthedocs build. Let's see whether that works.

Nothing happened here, yet. Might have to try with a new PR, could be that this one is somehow not tracked yet.

**Comment by steve-chavez** [comment]
I agree on 1.

2, 3 not so sure. These are the GA numbers on language:

2020-11-30-144309_740x355_scrot

So our second language is chinese. I believe this has to do with the chinese docs, although outdated, they might be serving as SEO. Chinese users probably visit the latest english docs afterwards.

Perhaps we should ask for help(pin issue)? That seemed to work for this one https://github.com/PostgREST/postgrest/issues/1445.

**Comment by wolfgangwalther** [comment]
> So our second language is chinese. I believe this has to do with the chinese docs, although outdated, they might be serving as SEO. Chinese users probably visit the latest english docs afterwards.

Can I see all the GA stuff somewhere? If not: You should be able to test your hypothesis by looking at the entrypoints or whatever that's called. `postgrest.org/zh/...` - how often is that requested? Looking at the other languages in the list and thinking about how many people speak those languages... my gut feeling would be that `zh-cn` is in fact underrepresented.

If it does in fact serve as SEO, then I might have a few other ideas how we could use that. Mainly creating translations of the homepage (index) for many more languages. This would contain most of the keywords (might have to add a few), is not updated frequently and chances are much higher that we could find people willing to keep those small changes up2date. If the index page in the other languages would then point to the main docs in english, that should be fine? We could create an english template for that, as it might be slightly different from the index page in english.

But keeping this translation of v.0.4 (not 4.0, 0.4 !!) around, when we don't even have that version in english anymore... uuh.

But first we should confirm that this really help SEO.

**Comment by wolfgangwalther** [comment]
I just took a look at the translation. It's not only outdated, but not even complete:
https://postgrest.org/zh/latest/api.html

Loads of english text there.

**Comment by wolfgangwalther** [comment]
Hey @Lellansin, maybe you can give your opinion on this? Steve and I have crunched the numbers a little bit and this is how it currently looks like:

As far as I can tell the chinese translation had not been finished. There was a little bit of progress earlier this year, but this is all still for a very old version of PostgREST: v.0.4, while we are currently at version 7.x. The traffic data for the readthedocs account says, that there is no traffic at all for the chinese translation. It does not seem to serve any SEO purpose and given that it's so outdated, it's very unlikely that this helps anyone using PostgREST. I assume it is quite a challenge by now to get those docs translated and up2date. I don't know how much the docs changed in the last 4 years, but just looking at the directory structure it looks like one would basically have to start from scratch anyway.

Do you think there is still value in keeping it around? Is there any chance that this will be continued to be worked on or finished?

My personal feeling is, that I don't like to pretend that we have translated docs, where we actually don't have anything to offer. I don't want to brag about things we don't really have. On a side-note: Good thing you managed to get those req/s up to 2000 again, @steve-chavez, ... ;).

Anyway my suggestion would be to remove the mention of the chinese translation here and also the integration with the readthedocs account. I would even go one step further and say we remove the translation hints completely, because I feel IF we can get anyone involved in this repo, it would be of much more value when they contributed to the english docs. We do have a bit of a backlog with 74 issues open here as well. Maybe we can replace this with some other section in the readme to increase engagement: Suggestions welcome!

Again, @Lellansin, would love to have your opinion on this, as this is/was your baby! Thanks!

**Comment by Lellansin** [comment]
Hi @wolfgangwalther, honestly, I'm not sure what's our purpose so that I cannot give you a direct answer. I think there may be some choices for us, like:

1. fix/update the zh-cn doc with that basis.
2. replace it with a new one.
3. keep our official docs with no confusion at least now (remove it first).

About 1st one, we can just follow the Github way, I mean list the problem then post issues or PR. The Chinese language is not very popular, a progressive Chinese document is not rare. For 2nd one, it's welcome. if we have plan, I'd like to join a part of it. If we only talk about 3rd one, it's a simple thing which won't need my confirm. 

We can chose one or two (like 1+3, 2+3), or any other purposes. As this is clear, we can discuss more about it.

**Comment by wolfgangwalther** [comment]
>     1. fix/update the zh-cn doc with that basis.
> 
>     2. replace it with a new one.
> 
>     3. keep our official docs with no confusion at least now (remove it first).
> 
> 
> About 1st one, we can just follow the Github way, I mean list the problem then post issues or PR. The Chinese language is not very popular, a progressive Chinese document is not rare. For 2nd one, it's welcome. if we have plan, I'd like to join a part of it. If we only talk about 3rd one, it's a simple thing which won't need my confirm.

Thanks for coming back to this so quickly. The reason I am asking you is quite simple: I don't know any Chinese. The only thing I could do would be 3. I can not help with 1 or 2. I can not even tell whether 1 or 2 would be the better way to do it.

I think the current situation needs one of those 3 solutions, you proposed. I am fine with any of the 3.

As you are the maintainer of the Chinese translation, this comes down to what your plans are. Do you want to and will you be able to do something about 1 or 2? If your answer is:
- Yes: Then I put this PR on hold for now.
- No: Then I will follow through with 3.

----

My personal opinion, again from the outside without knowing too much of the details: It looks like **a lot** of effort is needed to translate the PostgREST docs completely **and** keep them up2date with the main repo. I personally thought about doing the same for German - but quickly abandoned that thought again, because it would just be so much. I assume you would need a team of a couple of people to pull this through.

**Comment by Lellansin** [comment]
Well, remove the link dose not need my confirm.

And I'm solo with it, I didn't have team or plan, I did all the work with interest several years ago. I agree with you that up-to-date perfect status need huge effort to maintain, therefore, I thought the open source project need 
interested guys to make positive feedback. So, I guess the better way to help with existing version is list your advises to [postgrest-docs/issues](https://github.com/PostgREST/postgrest-docs/issues), I'd like to do sth with specific problems.

**Comment by wolfgangwalther** [comment]
> And I'm solo with it, I didn't have team or plan, I did all the work with interest several years ago. I agree with you that up-to-date perfect status need huge effort to maintain, therefore, I thought the open source project need
> interested guys to make positive feedback.

I very much appreciate the work you put into this! But as you say it's very hard to keep this up2date alone. Unfortunately I can't really help.

> So, I guess the better way to help with existing version is list your advises to [postgrest-docs/issues](https://github.com/PostgREST/postgrest-docs/issues), I'd like to do sth with specific problems.

I can't point out "specific problems". I just see those facts:
- https://github.com/Lellansin/postgrest-docs seems to be ~279 commits behind. The number alone doesn't say much, because merging those is not possible. But looking at the commit history it seems like those 279 commits have not been integrated in a translated version either. So the **content** of the translation is lagging **3-4 years** behind.
- The only translated files are `intro.rst`, `auth.rst`, `install.rst` and both the tutorials (tut1 still needs one section, but otherwise seems done).
- `admin.rst` and `api.rst` are not translated at all (except for some headers). There are a few new files by now, that are not even in the repo, yet.

I think the tutorials didn't change much over the years. I took a quick look at git blame, and big chunks are still 4 years old in the english version as well. So updating the tutorials to the current version might not be much work. The `intro.rst` (which is now `index.rst`), is probably something that will have fewer changes in the future as well. So with a bit of work right now, this could probably be kept up2date as well.

But I don't see any chance that `api.rst` and related pages will be translated. They had not been translated initially and are the most prone to updates. Also `api.rst` really is a page that **needs** to be up2date to have value. This is different for the tutorials - even if those are not 100% up2date, they still provide a lot of value.

----

Maybe the best way to go forward would be to just **reduce scope** a lot and say: We're only translating the `index.rst`  file and the tutorials. We will keep those reasonably up2date, so that they have value for beginners, who don't know much about PostgREST, yet. So the goal would not be to do a 100% translation, which is almost impossible. I could very well imagine to write something like that with very much reduced scope in German, too, and we could possibly find contributors for other languages as well.

What's your opinion @Lellansin - would "reducing scope" / change of goals make sense to you?

Not sure if "translation of the docs" is still the right term and how we would incorporate those into our english docs / website. Maybe it's more of a blog-post thing, only in different languages. Also if we publish it more in kind of a blog-format, they can never be out-of-date - because we have a timestamp on the blog and the blog post just reflects what was current at that time. Very much open for ideas here! @steve-chavez?

**Comment by steve-chavez** [comment]
@Lellansin Thanks a lot for the effort you put on the chinese docs. I know that it's a lot of work because I tried doing the same for Spanish - and then abandoned the idea.

@wolfgangwalther How about merging this PR(removing the links) and then opening/pinning an issue that asks for helps for the chinese docs? We can ref this issue there for someone that is willing to help. The blog posts idea sounds good, but before thinking too much about it, we should ask if someone is willing to help.

**Comment by Lellansin** [comment]
Wow, reduce scope is a good idea! It's a convenient way for us to make i18n. If there is a plan, which point out specific scope, I'd like to finish the `zh-cn` and `zh-tw` parts.

**Comment by wolfgangwalther** [comment]
I merged this and created #393 as a follow up.

**Pull request merged**
