### PR TITLE
Add embed disambiguation section

### PR DESCRIPTION
**Pull request by steve-chavez**
Work in progress..

Related to https://github.com/PostgREST/postgrest/pull/1430.

### CODE REVIEW

**Comment by steve-chavez** [comment]
Preview at https://postgrest.org/en/preview/api.html#embedding-disambiguation

**Comment by ruslantalpa** [comment]
the section is good and detailed but what I think it's missing is the "base documentation"  on how embeding works. It's very very underexplained. Only after a comprehensive section like this does the "disambiguation" section has meaning and is clear why it's relevant. Something along the lines of our chat:


When you want to embed a parent relation (many 2 one) you can either:
1.specify the table name and rename the key `billing:addresses(...)`
2. specify the foreign key and rename (if needed) it `billing:billing_id(...)`
3. specify the constraint name (which you can rename) `billing(...)`

When you want to embed a child relation (one 2 many):
...

When you want to embed a many 2 many relation:
...

**Comment by ruslantalpa** [comment]
also the fact that embedding is recursive/can be nested needs to be mentioned somewhere with an example

**Comment by steve-chavez** [comment]
@ruslantalpa I see what you mean. That's a section I had in mind. I wanted to call it something like: `Resource embedding cardinality` and mention the `o2m/m2o/m2m` possibilities(btw we're missing an `o2o` there for completeness). I think this can be added later.

The other stuff is a section about aliasing/renaming the embedded resource, I think this could be added now.

**Comment by steve-chavez** [comment]
> Resource embedding cardinality... I think this can be added later...

I mention this because I've avoided mentioning the particular case of `m2m` disambiguation with the `junction` table. Instead just gave the users the tools to disambiguate. If they get an error message it should be clear enough what to do once they read this section. Otherwise it would get too long. Not all users will hit the same edge cases and adding all possible cases would be confusing.

**Comment by steve-chavez** [comment]
About recursive embeds, there's another issue for that https://github.com/PostgREST/postgrest-docs/issues/275.

**Comment by steve-chavez** [comment]
I've added another issue for aliasing https://github.com/PostgREST/postgrest-docs/issues/292. It could be added separately from disambiguation.

I'd like to merge the disambiguation feature and doc now, it has been open for a while.

**Pull request merged**
