### PR TITLE
fix: remove net option from docker cmd

### PR DESCRIPTION
**Pull request by cemremengu**
net and port binding options cannot be used together

### CODE REVIEW

**Comment by wolfgangwalther** [comment]
Hm. This falls a bit short. There is a whole paragraph about macOS not supporting `--net` - which would be useless after the change.

But before we go ahead and rip that out, too: Will removing the `--net` even work? The example is about a dockerized postgrest with postgresql on the host machine. So there should still be some way to connect to the database - and `localhost` won't do it.

Wouldn't the solution be to remove the `port` instead, because when using `--net=host`, postgrest will listen on `localhost:3000` anyway?

**Comment by cemremengu** [comment]
Docker ignores the `port` when `--net` is present i.e: `WARNING: Published ports are discarded when using host network mode`

However, I didn't know about macOS so in that case we can keep this as is.

and yes this is correct

> Wouldn't the solution be to remove the port instead, because when using --net=host, postgrest will listen on localhost:3000 anyway?

**Comment by wolfgangwalther** [comment]
I'll reopen this, because I think we should in fact do *something* about it. Having that warning seems not useful. Not sure what exactly, we'll do, but this will keep it visible for now.

**Comment by steve-chavez** [comment]
Maybe we need tabs(like we do for the curl/http snippets) for the docker installation methods.

**Comment by wolfgangwalther** [comment]
Fixed this in #499.

**Pull request closed without merging**
